name: Generate Post

on:
  schedule:
    - cron: '0 0 * * 1' # Every Monday
    - cron: '0 0 * * 4' # Every Thursday
  workflow_dispatch:

jobs:
  generate-post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate new post
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: echo $(pwd) && python post_generator.py

      # Commit changes (new post) back to repo
      - name: Commit new post
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add content/
          git commit -m "chore: add new post [skip ci]" || echo "No changes to commit"
          git push
